apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-pvc
  labels:
    app: busybox-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-pvc
  template:
    metadata:
      labels:
        app: busybox-pvc
    spec:
      containers:
      - name: busybox-pvc
        image: busybox
        command: ['sh', '-c', "echo Hello PVC! && sleep 3600"]
        volumeMounts:
        - mountPath: /tmp/
          name: my-storage
      volumes:
      - name: my-storage
        persistentVolumeClaim:
          claimName: pvc
