apiVersion: v1
kind: Pod
metadata:
  name: conf-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: confname
      valueFrom:
        configMapKeyRef:
          name: conf
          key: name
