apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-resources
  namespace: default
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "1"
    requests.memory: 1Gi
status:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "1"
    requests.memory: 1Gi
  used:
    limits.cpu: 500m
    limits.memory: 128Mi
    requests.cpu: 250m
    requests.memory: 64Mi
