apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-admin
  namespace: test
subjects:
- kind: User
  name: nan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: admin
  apiGroup: rbac.authorization.k8s.io
cloud_user@b62f5601561c:~$ kubectl apply -f role-binding.yaml 
rolebinding.rbac.authorization.k8s.io/pod-admin created
